name: Website pa11y tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  check-a11y:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      
    - name: Install node 
      uses: actions/setup-node@v1
      with:
        node-version: "12.x"

    - name: Install pa11y
      run: npm ci
    
    - name: Cache dependencies - Node 
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-s

    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7' # Match the runtime version in CloudFare
    
    - name: Install dependencies
      run: python -m pip install -r requirements.txt

    - name: Cache dependencies - Python
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Build site
      continue-on-error: true
      run: nikola build

    - name: Upload site
      continue-on-error: true
      uses: actions/upload-artifact@v2
      with:
        name: labs-site
        path: output/

    - name: Check site a11y
      continue-on-error: true
      run: |
        nikola auto & sleep 10
        npm run test-pa11y | tee pa11y_output.txt
